// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVMB-X4zM23kShvBNM1nOqdkbdFyBA79A',
    appId: '1:289390727360:web:57f763f30b8fbfd16a5d25',
    messagingSenderId: '289390727360',
    projectId: 'authenticationapp-a96ee',
    authDomain: 'authenticationapp-a96ee.firebaseapp.com',
    storageBucket: 'authenticationapp-a96ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbf3QB3YcbPayil7N_3g9YLR4XNrlTNOc',
    appId: '1:289390727360:android:29ebb9b9d3be7f586a5d25',
    messagingSenderId: '289390727360',
    projectId: 'authenticationapp-a96ee',
    storageBucket: 'authenticationapp-a96ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIZVFgiPVKcOzsQ0tDdnt6uLucgeCftFs',
    appId: '1:289390727360:ios:dfc7f68a655632326a5d25',
    messagingSenderId: '289390727360',
    projectId: 'authenticationapp-a96ee',
    storageBucket: 'authenticationapp-a96ee.appspot.com',
    iosClientId: '289390727360-6p79pn8i2q393qt95etgne351itkmse2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gatekeeper',
  );
}
